apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: om3iawj0z-python
  janus-idp.io/tekton: om3iawj0z-python
  backstage.io/kubernetes-id: om3iawj0z-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: om3iawj0z-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
